// File generated by FlutterFire CLI.
// This file should be included in your Flutter project to configure Firebase.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for the current platform.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can add these by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can add these by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can add these by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web configuration from your Firebase project
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxOjV21bZUKE3KTc8ilIbgCuZ5kgBfgAQ',
    appId: '1:422585181545:android:9e18d2763ffbf5bfd8c9f8',
    messagingSenderId: '422585181545',
    projectId: 'tabebak-9a2c4',
    authDomain: 'tabebak-9a2c4.firebaseapp.com',
    storageBucket: 'tabebak-9a2c4.firebasestorage.app',
  );

  // Android configuration from your Firebase project
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxOjV21bZUKE3KTc8ilIbgCuZ5kgBfgAQ',
    appId: '1:422585181545:android:9e18d2763ffbf5bfd8c9f8',
    messagingSenderId: '422585181545',
    projectId: 'tabebak-9a2c4',
    storageBucket: 'tabebak-9a2c4.firebasestorage.app',
  );

  // iOS configuration - use default values since we don't have specific iOS config
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxOjV21bZUKE3KTc8ilIbgCuZ5kgBfgAQ',
    appId: '1:422585181545:android:9e18d2763ffbf5bfd8c9f8',
    messagingSenderId: '422585181545',
    projectId: 'tabebak-9a2c4',
    storageBucket: 'tabebak-9a2c4.firebasestorage.app',
    iosClientId: '1:422585181545:ios:9e18d2763ffbf5bfd8c9f8',
    iosBundleId: 'com.example.tabebak',
  );
}
